# Generated by Django 6.1 on 2026-08-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AM Enterprises', max_length=120)),
                ('slogan', models.CharField(default='Your trust, our commitment', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_address', models.TextField(blank=True)),
                ('about_blurb', models.TextField(blank=True, default='AM Enterprises supplies trusted household products for everyday living. Your trust, our commitment.')),
                ('currency', models.CharField(default='PKR', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
